# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec24376157263e0802928051dd08acd9bc9486a712d2291846078f9addff6e2a7220faa09e9f1986b491f8fcd5987f2c2b5c6bfc2a5166f331f3a06f63fca61

test:
  secret_key_base: 17ed2204a3ab77e0e4a16d4c5109d1d007ab1f7820cc6d12a3cf08a422edef76c9aafe38d1e0b24fc7e4e2d8bb86c2ca4297278c511ccfe6f7166e04e7eccc67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
